export const categories = [
    {
      category: "CLEANING",
      services: [
        "End of Tenancy Cleaning",
        "Domestic Cleaning",
        "Oven/BBQ Cleaning",
        "Upholstery Cleaning",
        "Window Cleaning",
        "Carpet/Rug Cleaning",
        "Antiviral Sanitisation",
        "Pressure Washing",
        "Gutter Cleaning",
        "Ironing",
        "After Builders Cleaning",
        "Holiday Rental Cleaning",
        "Vehicle Sanitisation",
        "Hard Floor Cleaning",
        "Curtains and Blinds Cleaning",
      ],
    },
    {
      category: "GARDENING & LANDSCAPING",
      services: [
        "Garden Maintenance",
        "Garden Clearance",
        "Lawn Mowing",
        "Pressure Washing",
        "Landscaping Survey",
        "Tree Surgery",
      ],
    },
    {
      category: "REMOVALS",
      services: [
        "Removals",
        "Moving To Storage",
        "Man & Van",
        "Boxes Delivery",
        "Packing Service",
        "Furniture Assembly",
        "Office Removals Survey",
      ],
    },
    {
      category: "WASTE REMOVAL",
      services: [
        "Household Waste",
        "Green Waste Removal",
        "Builders Waste",
        "Office Clearance",
        "Loft/Cellar Clearance",
        "Christmas Tree Recycle",
        "Appliance Disposal",
      ],
    },
  ];